const successCopy: Record<string, string> = {
  "Customer created.": "Client created",
  "Customer updated.": "Client updated",
  "Dashboard item saved.": "Dashboard configuration saved",
  "Follow-up automation saved.": "Follow-up automation saved",
  "Follow-up saved.": "Follow-up scheduled",
  "Intake field added.": "Intake field added",
  "Intake field disabled.": "Intake field disabled",
  "Intake field saved.": "Intake field saved",
  "Intake form settings saved.": "Intake settings saved",
  "Contact recorded.": "Marked contacted",
  "Job created.": "Opportunity created",
  "Job marked lost.": "Marked lost",
  "Job updated.": "Opportunity updated",
  "Photo uploaded.": "Photo uploaded",
  "Photos uploaded.": "Photos uploaded",
  "Pipeline status saved.": "Pipeline saved",
  "Quote accepted.": "Proposal accepted",
  "Quote accepted. Thank you.": "Proposal accepted",
  "Quote declined.": "Proposal declined",
  "Quote marked sent.": "Proposal sent",
  "Quote question resolved.": "Question marked answered",
  "Quote recorded.": "Proposal recorded",
  "Quote saved.": "Proposal saved",
  "Service type added.": "Service type added",
  "Service type disabled.": "Service type disabled",
  "Service type saved.": "Service type saved",
  "Status changed.": "Status changed",
  "Action added.": "Action added",
  "Action playbook saved.": "Action playbook saved",
  "Terminology saved.": "Terminology saved",
  "Message sent.": "Message sent",
  "Public intake settings saved.": "Intake settings saved",
  "Reply already sent.": "Reply already sent",
  "Reply sent.": "Reply sent",
  "Workspace created with default configuration.": "Workspace created",
  "Workspace invite accepted. Welcome to FlowDeck.": "Workspace invite accepted",
  "Workspace settings saved.": "Workspace settings saved",
  "Workspace updated.": "Workspace settings saved",
};

export function successFeedbackMessage(message?: string | null) {
  if (!message) return null;
  return successCopy[message] ?? null;
}
